export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const BASCKET_ROUTE = '/bascket'
export const PRODUCT_ROUTE = '/product'
export const SHOP_ROUTE = '/'